#server:
#  port: 1000 # 服务器端口
#
#spring:
#  application:
#    name: cloud-provider # Spring 应用名
#  cloud:
#    nacos:
#      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
#      discovery:
#        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
##        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
#        namespace: 08299dfe-7f66-40aa-9877-2bdc02cf6277 # Nacos 命名空间 dev 的编号
