#server:
#  port: 1001 # 服务器端口
#
#spring:
#  application:
#    name: cloud-client # 服务消费者
#  cloud:
#    nacos:
#      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
#      discovery:
#        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
##        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
##        namespace: 08299dfe-7f66-40aa-9877-2bdc02cf6277 # Nacos 命名空间 dev 的编号
#
#    # Sentinel 配置项，对应 SentinelProperties 配置属性类
#    sentinel:
#      enabled: true # 是否开启。默认为 true 开启
#      eager: true # 是否饥饿加载。默认为 false 关闭
#      transport:
#        dashboard: 127.0.0.1:8080 # Sentinel 控制台地址
#      filter:
#        url-patterns: /** # 拦截请求的地址。默认为 /*
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
#  endpoint:
#    # Health 端点配置项，对应 HealthProperties 配置类
#    health:
#      enabled: true # 是否开启。默认为 true 开启。
#      show-details: ALWAYS # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
#
#
#dubbo:
#  scan:
#    base-packages: com.cloud.service # 指定 Dubbo 服务实现类的扫描基准包
#  # Dubbo 服务暴露的协议配置，对应 ProtocolConfig Map
#  protocols:
#    dubbo:
#      name: dubbo # 协议名称
#      port: -1 # 协议端口，-1 表示自增端口，从 20880 开始
#  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
#  registry:
#    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
#  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
#  cloud:
#    subscribed-services: cloud-provider # 设置订阅的应用列表，默认为 * 订阅所有应用
